project:
  type: website

number-sections: false

format:
  html:
    toc: true
    toc-location: right
    page-navigation: true
    theme: sandstone
    css: style.css
    # page-layout: full

website:
  favicon: "images/nav-logo.jpeg"
  site-url: "https://www.jjd.io"
  twitter-card:
    site: "@omgjjd"
    card-style: "summary_large_image"
  image : "images/me.jpeg"
  open-graph: true
  title: "Justin Donaldson, Ph.D."
  body-footer: "<i>Â© Copyright 2024 Justin Donaldson. Except where otherwise noted, all rights reserved. The views and opinions on this website are my own and do not represent my current or former employers.</i>"
  navbar:
    logo : "images/nav-logo.png"
    left:
      - index.qmd
      - text: "blog"
        href: blog.qmd
      - text: "cv"
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/jdonaldson
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/omgjjd
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/jjustindonaldson/
        aria-label: Linkedin
      - icon: vinyl-fill
        href: https://www.discogs.com/user/omgjjd
        aria-label: Discogs

  google-analytics: "G-J1DD0F3VY9"

execute:
  freeze: auto

resources:
  - CNAME
